"""Constants for the room component."""

DOMAIN = "room"
CONF_ROOM = "room"
ATTR_RADIUS = "radius"
ATTR_COORDS = "coordinates"
ATTR_STATUS = "status"
ATTR_STATE = "state"
ATTR_CONTEXT = "context"
ATTR_COMMAND = "command"
ATTR_RESPONSE = "response"

SERVICE_SET_STATUS = "set_status"
SERVICE_SET_CONTEXT = "set_context"
SERVICE_SET_COMMAND = "set_command"
SERVICE_SET_RESPONSE = "set_response"
