reload:

set_status:
  target:
    entity:
      domain: room
  fields:
    status:
      example: "weapon"
      selector:
        select:
          options:
            - "ok"
            - "weapon"
            - "fire"
            - "medical"
            - "weather"
            - "suspicious"
            - "conflict"
